1. What is a Python library? Why ^o we use Python libraries?


In [ ]:
#A Python library is a collection of modules or packages that contain pre-written code to perform specific tasks. We use Python libraries to save time and effort by leveraging existing functionalities rather than writing everything from scratch

2. What is the ^ifference between Numpy array an^ List?


In [ ]:
#The main differences between a NumPy array and a list are:

#NumPy arrays are homogeneous, meaning all elements must be of the same data type, while lists can contain elements of different data types.
#NumPy arrays offer more efficient storage and operations for numerical data.
#NumPy arrays support vectorized operations, making it easier to perform element-wise operations without explicit looping.

In [1]:
import numpy as np

# 3. Find the shape, size and dimension of the given array
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print("Shape:", arr.shape)
print("Size:", arr.size)
print("Dimension:", arr.ndim)

Shape: (3, 4)
Size: 12
Dimension: 2


In [2]:
# 4. Write Python code to access the first row of the array
first_row = arr[0, :]
print("First Row:", first_row)

First Row: [1 2 3 4]


In [4]:
# 5. Access the element at the third row and fourth column
element_3rd_row_4th_col = arr[2, 3]
print("Element at 3rd row, 4th column:", element_3rd_row_4th_col)

Element at 3rd row, 4th column: 12


In [5]:
# 6. Code to extract all odd-indexed elements
odd_indexed_elements = arr[:, 1::2]
print("Odd-indexed elements:", odd_indexed_elements)

Odd-indexed elements: [[ 2  4]
 [ 6  8]
 [10 12]]


In [6]:
# 7. Generate a random 3x3 matrix with values between 0 and 1
random_matrix = np.random.rand(3, 3)
print("Random 3x3 Matrix:", random_matrix)

Random 3x3 Matrix: [[0.61964421 0.09923251 0.10720634]
 [0.96839478 0.36551834 0.93953116]
 [0.73255652 0.4892666  0.08975614]]


8. Describe the ^ifference between np.ran^om.ran^ an^ np.ran^om.ran^n?


In [ ]:
#The difference between np.random.rand and np.random.randn is that the former generates random values from a uniform distribution between 0 and 1, while the latter generates values from a standard normal distribution (mean=0, standard deviation=1).

In [7]:
# 9. Code to increase the dimension of the array
increased_dimension = np.expand_dims(arr, axis=0)
print("Increased Dimension:", increased_dimension)

Increased Dimension: [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [8]:
# 10. Transpose the array
transposed_array = np.transpose(arr)
print("Transposed Array:\n", transposed_array)


Transposed Array:
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [12]:
# 11. Matrix operations
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
B = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Matrix addition
addition_result = A + B

# Matrix multiplication (element-wise)
elementwise_multiply_result = A * B

# Matrix multiplication (dot product)
matrix_multiply_result = np.dot(A, B.T)

# Matrix subtraction
subtraction_result = B - A

# Matrix division
division_result = B / A

print("Matrix Addition:\n", addition_result)
print("Element-wise Multiplication:\n", elementwise_multiply_result)
print("Matrix Multiplication (Dot Product):\n", matrix_multiply_result)
print("Matrix Subtraction:\n", subtraction_result)
print("Matrix Division:\n", division_result)


Matrix Addition:
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
Element-wise Multiplication:
 [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
Matrix Multiplication (Dot Product):
 [[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]
Matrix Subtraction:
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Matrix Division:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
# 12. Swap byte order of an array
arr = np.array([1, 2, 3, 4], dtype=np.int32)
swapped_arr = arr.byteswap()
print("Swapped Byte Order Array:", swapped_arr)


In [ ]:
# 13. Significance of np.linalg.inv function
# The np.linalg.inv function calculates the inverse of a matrix. It is significant in linear algebra for solving systems of linear equations.


In [ ]:
# 14. np.reshape function
# np.reshape is used to change the shape of an array. It returns a new array with the specified shape.

In [ ]:
# 15. Broadcasting in Numpy
# Broadcasting is a feature in NumPy that allows operations between arrays of different shapes and sizes.